### ISSUE TITLE
Error when show IconDialog on release app

### ISSUE THREAD

**Issue by jrcacd** [maltaisn/icondialoglib#13]
```
val iconDialog = IconDialog()
iconDialog.show(activity.supportFragmentManager, "icon_dialog")
```

**Error**
```
java.lang.NumberFormatException: For input string: "string/icd_category_people"
        at java.lang.Integer.parseInt(Integer.java:608)
        at java.lang.Integer.valueOf(Integer.java:794)
        at qN.a(SourceFile:19)
        at nN.run(SourceFile:3)
        at xN.run(SourceFile:1)
```
Do we have to add something to proguard so this error is fixed?

**Comment by maltaisn** [comment]
Since the strings are only referenced in `res/xml/icd_icons.xml` it may be possible proguard doesn't keep them. I'll look into it.

**Comment by maltaisn** [comment]
I could not reproduce the issue with minify enabled and shrink resources. Do you have any specific proguard rules? The configuration file I used is empty.

**Comment by jrcacd** [comment]
Android studio is running R8.

```
-dontpreverify
-repackageclasses ''
-allowaccessmodification

-optimizations !code/simplification/arithmetic
-optimizations !code/allocation/variable

-printmapping out.map
-renamesourcefileattribute SourceFile

-keepattributes SourceFile    
-keepattributes LineNumberTable 
-keepattributes Exceptions     
-keepattributes Signature       
-keepattributes *Annotation*   
-keepattributes EnclosingMethod

-dontnote android.net.http.*
-dontnote org.apache.commons.codec.**
-dontnote org.apache.http.**

-keep public class * extends java.lang.Exception


#Kotlin
-dontwarn kotlin.**
-keepclassmembers class **$WhenMappings { <fields>; }
-assumenosideeffects class kotlin.jvm.internal.Intrinsics {
    static void checkParameterIsNotNull(java.lang.Object, java.lang.String);
}


#----------------------------------
#Android http
-keep,allowshrinking class com.loopj.android.http.** { *; }
-keep,allowshrinking interface com.loopj.android.http.** { *; }

#----------------------------------
# support design
-dontwarn android.support.design.**
-keep,allowshrinking class android.support.design.** { *; }
-keep,allowshrinking interface android.support.design.** { *; }
-keep,allowshrinking public class android.support.design.R$* { *; }
-keep class android.support.v7.widget.SearchView { *; }


# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}


# EventBus 3.0
-keepattributes *Annotation*
-keepclassmembers class ** { @org.greenrobot.eventbus.Subscribe <methods>; }
-keep,allowshrinking enum org.greenrobot.eventbus.ThreadMode { *; }
-keep,allowshrinking class de.greenrobot.event.** { *; }

#mikepenz/AboutLibraries------------------------
-keep class .R
-keep class **.R$* { <fields>; }

-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int intent(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
    public static *** d(...);
}

-keepclassmembernames class * {
    java.lang.Class class$(java.lang.String);
    java.lang.Class class$(java.lang.String, boolean);
}


-keepclasseswithmembernames, includedescriptorclasses class * { native <methods>; }
-keepclasseswithmembers class * { public <init>(android.content.Context, android.util.AttributeSet); }
-keepclasseswithmembers class * { public <init>(android.content.Context, android.util.AttributeSet, int); }

-keep,allowshrinking public class * extends android.app.Activity
-keep,allowshrinking public class * extends android.app.Application
-keep,allowshrinking public class * extends android.app.Service
-keep,allowshrinking public class * extends android.content.BroadcastReceiver
-keep,allowshrinking public class * extends android.content.ContentProvider
-keep                public class * extends android.preference.Preference

-keep,allowshrinking public class * extends android.view.View {
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
    public void set*(...);
}

-keepclassmembers,allowshrinking class * extends android.content.Context {
   public void *(android.view.View);
   public void *(android.view.MenuItem);
}

-keepclassmembers,allowshrinking class * implements android.os.Parcelable { static ** CREATOR; }


-keepclassmembers,allowshrinking class * { @android.webkit.JavascriptInterface <methods>; }


-keepclassmembers,allowshrinking,allowoptimization enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keepclassmembers,allowshrinking class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep,allowshrinking class sun.misc.Unsafe { *; }
-keep,allowshrinking class com.google.gson.stream.** { *; }



-keep,allowshrinking class com.google.android.gms.internal.** { *; }

# Application classes that will be serialized/deserialized over Gson
-dontwarn sun.misc.Unsafe

-keepclassmembers enum * { *; }

# Prevent proguard from stripping interface information from TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep,allowshrinking class * implements com.google.gson.TypeAdapterFactory
-keep,allowshrinking class * implements com.google.gson.JsonSerializer
-keep,allowshrinking class * implements com.google.gson.JsonDeserializer
##---------------End: proguard configuration for Gson  ----------
```

**Comment by maltaisn** [comment]
I have enabled R8 and used the same proguard settings but still cannot reproduce the crash. 

This seems to be happening in `IconHelper` at line 311, because the XML resource reference wasn't converted correctly to an integer at build time. Normally aapt would change `string/icd_category_people` to an int like `0x7f907534`, which can be parsed by the library. I don't know why this is not happening. Do you think you can check your proguard mapping to deobfuscate the stack trace and confirm this?

This doesn't seem to be related to proguard, the category name strings are there in the release APK.

**Comment by jrcacd** [comment]
```
Fatal Exception: java.lang.NumberFormatException
For input string: "string/icd_category_people"

     java.lang.Integer.parseInt (Integer.java:608)
     java.lang.Integer.valueOf (Integer.java:794)
     com.maltaisn.icondialog.IconHelper.loadIcons (SourceFile:312)
     com.maltaisn.icondialog.IconHelper$1.com.maltaisn.icondialog.IconHelper.access$100 (SourceFile:110)
     com.maltaisn.icondialog.TaskExecutor$1.run (SourceFile:27)
```

**Comment by maltaisn** [comment]
Can you also take a look at the generated APK? (Build > Build APK. Then Analyse). Look for the `icd_icons.xml` in `res/xml` and check if `<category>` tags have an ID at the `name` attribute, like this `<category id="0" name="@ref/0x7f0b003e">`.

**Comment by jrcacd** [comment]
> Can you also take a look at the generated APK?

We are generationg android bundle.

> `icd_icons.xml` in `res/xml`

```
<category
        id="0"
        name="@string/icd_category_people" >
        <icon
            id="0"
            labels="account,user,person"
            path="M12 4a4 4 0 1 1 0 8 4 4 0 0 1 0-8zm0 10c4.418 0 8 1.79 8 4v2H4v-2c0-2.21 3.582-4 8-4z" />
...
```

**Comment by maltaisn** [comment]
Does it work in debug build? I feel like this is more of an AAPT bug, perhaps related to using bundles...

As a workaround, you can make a custom build of the library, where you change the name attribute of every `<category>` tag to include only the string name (i.e: change `name="@string/icd_category_people"` to `name="icd_category_people"`). Then change line 312 of [`IconHelper`](https://github.com/maltaisn/icondialoglib/blob/master/icondialog/src/main/java/com/maltaisn/icondialog/IconHelper.java#L312)  to:
```java
int resId = (nameStr == null ? 0 : context.getResources().getIdentifier(nameStr, "string", context.getPackageName());
```
Don't forget to add `tools:keep` for every category string, since they're not referenced anymore.

**Comment by jrcacd** [comment]
> Does it work in debug build?

Yes, works fine.

**Comment by jrcacd** [comment]
Why the code is doing this?
https://github.com/maltaisn/icondialoglib/blob/81f35ab8620d81a8dac27277a764ab0fbe4aa275/icondialog/src/main/java/com/maltaisn/icondialog/IconHelper.java#L312
`Integer.valueOf(nameStr.substring(1)));`

Why convert nameStr to int? Does it contain numbers?

**Comment by maltaisn** [comment]
Normally the string reference is converted to a string like `@2131427390` at build time, where the number is a resource ID.

I think I'll change that part to use `getIdentifier` if the string is not a number and I'll make a new release shortly.

**Comment by maltaisn** [comment]
I changed it. Can you clone the repo and add the icondialog module to your project to test it, before I make a release?

**Comment by jrcacd** [comment]
Yes, now it works fine!!!

**Comment by maltaisn** [comment]
I released a new version with the fix.

**Comment by jrcacd** [comment]
Thanks
