### ISSUE TITLE
Example app crashed.

### ISSUE THREAD

**Issue by KaanRF** [maltaisn/icondialoglib#35]
I wanted to let it run the demo app on my emulator and it is has been crashed when I wanted to click fab button to select icon. 

```
2020-04-19 12:17:02.013 4444-4444/com.maltaisn.icondialoglib.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.maltaisn.icondialoglib.demo, PID: 4444
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/KotlinPackage;
        at com.maltaisn.icondialog.IconDialog.onCreateDialog(IconDialog.kt:111)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.KotlinPackage" on path: DexPathList[[zip file "/data/app/com.maltaisn.icondialoglib.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.maltaisn.icondialoglib.demo-1/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.maltaisn.icondialog.IconDialog.onCreateDialog(IconDialog.kt:111) 
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380) 
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by maltaisn** [comment]
I tried to reproduce this by removing all Kotlin dependencies but it still works fine,, both on the emulator and on a physical device. Same with #34, I don't get an IDE error. I think you might have some luck by adding the kotlin dependency to your project:
```
implementation "org.jetbrains.kotlin:kotlin-stdlib:1.3.70"
```
But it worked for me without it. For the IDE error try cleaning the caches (Invalid caches & restart). Otherwise it seems there's not much I can do.

**Comment by KaanRF** [comment]
> I tried to reproduce this by removing all Kotlin dependencies but it still works fine,, both on the emulator and on a physical device. Same with #34, I don't get an IDE error. I think you might have some luck by adding the kotlin dependency to your project:
> 
> ```
> implementation "org.jetbrains.kotlin:kotlin-stdlib:1.3.70"
> ```
> 
> But it worked for me without it. For the IDE error try cleaning the caches (Invalid caches & restart). Otherwise it seems there's not much I can do.

Thanks for your quick reply, I will try to use latest library again when I have time for the issue #34 . 
But here is my gradle files may be you will incidently catch something. 

:app
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.android.gms.oss-licenses-plugin'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "MyApp"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode xxx
        versionName "xxxx"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation":
                                     "$projectDir/schemas".toString(),]
            }
        }
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            res.srcDirs = [
                    file("src/main/res/layouts/").listFiles(),
                    "src/main/res/layouts",
                    "src/main/res"
            ]
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    lintOptions {
        lintConfig file("lint.xml")
        // set to true to turn off analysis progress reporting by lint
        quiet false

        explainIssues true
        // if true, stop the gradle build if errors are found
        abortOnError false
        warningsAsErrors false
        // if true, only report errors
        ignoreWarnings false

        checkReleaseBuilds false

        disable 'MissingTranslation'
    }

    repositories {
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
}

dependencies {
    def lifecycle_version = "2.2.0"
    def room_version = '2.2.5'
    def navigation_version = "2.2.2"
    def material_version = "1.1.0"
    def constraint_layout_version = "1.1.3"
    def work_version = '2.3.4'

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.cardview:cardview'
    implementation "com.google.android.material:material:$material_version"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "androidx.constraintlayout:constraintlayout:$constraint_layout_version"
    implementation "androidx.navigation:navigation-fragment:$navigation_version"
    implementation "androidx.navigation:navigation-ui:$navigation_version"
    implementation "androidx.work:work-runtime:$work_version"

    // Test
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    // Optional -- Robolectric environment
    testImplementation 'androidx.test:core:1.2.0'
    // Optional -- Mockito framework
    testImplementation 'org.mockito:mockito-core:3.3.0'

    // lifecycle components.
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
    // Annotation processor
    annotationProcessor "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata:$lifecycle_version"
    // Lifecycle only (without ViewModel or LiveData)
    implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
    // Saved state module for ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"
....
    // Kotlin related
    implementation 'androidx.core:core-ktx:1.3.0-rc01'
    implementation 'org.jetbrains:annotations:18.0.0'
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```
:MyApp
```
buildscript {
    ext.kotlin_version = '1.3.61'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.android.gms:oss-licenses-plugin:0.10.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

It can be a problem on my emulator or the setting of the Android stduio which I am using now. 

![image](https://user-images.githubusercontent.com/3770937/79909624-f6f30700-8425-11ea-9046-6d979ca9e248.png)


By the way I pulled the latest master branch and compiled for the example app. I think still the same error I got, 
My emulator 
![image](https://user-images.githubusercontent.com/3770937/79909515-c7dc9580-8425-11ea-814f-99d399367193.png)

```
2020-04-21 23:12:35.546 4916-4916/com.maltaisn.icondialoglib.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.maltaisn.icondialoglib.demo, PID: 4916
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/KotlinPackage;
        at com.maltaisn.icondialog.IconDialog.onCreateDialog(IconDialog.kt:111)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.KotlinPackage" on path: DexPathList[[zip file "/data/app/com.maltaisn.icondialoglib.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.maltaisn.icondialoglib.demo-2/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.maltaisn.icondialog.IconDialog.onCreateDialog(IconDialog.kt:111) 
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380) 
        at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
2020-04-21 23:12:36.197 1343-1343/? E/EGL_emulation: tid 1343: eglCreateSyncKHR(2050): error 0x3004 (EGL_BAD_ATTRIBUTE)
2020-04-21 23:12:36.317 2526-2685/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
```

**Comment by maltaisn** [comment]
Try replacing this line:
```gradle
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
```
with this one:
```
implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
```
The library uses `kotlin-stdlib` but you use `kotlin-stdlib-jdk7`, so maybe that's the cause of the problem? I'm just trying to guess things here.

**Comment by KaanRF** [comment]
> implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

I tried this. At this time I did not get the error report from the Android Studio for the JetBrains like above but now Android studio is freeze that I can not reach the objects from your library.  I did several times "invalide cache and restart" but it works only one time. When I import the class it is freeze itself then no any auto complete or copy paste  is working. Too weird.

And weirdly he import like below. 

![image](https://user-images.githubusercontent.com/3770937/80291844-bebb3380-8759-11ea-9a96-9a7069ad5768.png)

I could only IconPack succesfully import. 
![image](https://user-images.githubusercontent.com/3770937/80291847-d1356d00-8759-11ea-9297-f304a6d3a7b5.png)

New edit: I realize that after so many "Invalide cache and restart" processes I tried to use the latest library. Whenever I use the auto compilation for IconPack android studio is freeze and stop auto complete or copy paste. this is really too weird 😨 . 

I assume I got the error on the issue #34 because of the order plugin in my gradle file as you can see on my above reply I attached my gradle file and order was like below ; 

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.android.gms.oss-licenses-plugin'
```
So now I changed to like below because there was a warning as 

>  Kotlin plugin should be enabled before ‘kotlin-kapt 
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.android.gms.oss-licenses-plugin'
apply plugin: "androidx.navigation.safeargs"
```
After this changes I did not get the error report on my Android studio like issue #34 


**And also since I already ask this question on the issue #34  could you please give me an answer ? it is important for me. If I can not find the solution I will stay the version 2.5.0 for the future and try to update when I convert my app to kotlin. But if there is a problem like below questions I have doubt. Because my app users will be already save the icon id s on their databases and when I update the icon lib their customization will be lost. 

Questions from #34 
1. And also what is the successor of the IconView with the version 3.2.0 ? Is there any migration documents ? I just read the release notes but I could not find such a documentation.

- [ ] answer is added.

2. I save the some icond id s in my app to database. When app new started with this saved ids I read the icons via IconHelper past. When I switcht to version 3.2.0 will the icon id s will be same ? or the icons now has new id ?

- [ ] answer is added.

**Comment by maltaisn** [comment]
> After this changes I did not get the error report on my Android studio like issue #34

Great! I didn't know that plugin order could be important. 

I missed the other questions last time, sorry.

> What is the successor of the IconView with the version 3.2.0 ? Is there any migration documents ? I just read the release notes but I could not find such a documentation.

I removed it because what used to be the `IconHelper` singleton is now icon packs. Unlike `IconHelper`, icon packs cannot *always* be retrieved with just a context. In the example application, icon pack *can* be retrieved with just a context, but user is free to store the icon pack anywhere (in an architecture components ViewModel for instance), so making an `IconView` handling all possible cases would be impossible.

But if you take a look at the source for [`IconView.java`](https://github.com/maltaisn/icondialoglib/blob/91335e8ad624ed73aeda06a3c25e11c28dd5ab6f/icondialog/src/main/java/com/maltaisn/icondialog/IconView.java), you'll see that it was really just a very simple wrapper around ImageView, so replacing it isn't difficult.

Assuming you store the icon pack in the `App` class like in the wiki example, you can set an icon on any ImageView like this: (this code would be in a fragment, but it works in activity too.)
```java
ImageView imv = view.findViewById(R.id.image_view);

IconDrawableLoader drawableLoader = new IconDrawableLoader(requireContext());  // Loader needed to load icon drawables.
IconPack iconPack = ((App) requireContext().getApplicationContext()).getIconPack();  // Get icon pack from application class.

Drawable iconDrawable = iconPack.getIconDrawable(iconId, drawableLoader);  // Get icon drawable from icon pack.
if (iconDrawable == null) {
    // Handle case where icon is missing or failed to load.
} else {
    imv.setDrawable(iconDrawable);
}
```
If you find yourself doing this in a lot of places, you can always bundle it in your own custom view.

> I save the some icond id s in my app to database. When app new started with this saved ids I read the icons via IconHelper past. When I switch to version 3.2.0 will the icon id s will be same ? or the icons now has new id ?

Yes, if you use `iconpack-default` the IDs are all the same as before. There's no changes in the icons between 2.5.0 and 3.2.0. But that doesn't mean you shouldn't handle `null` values when retrieving a drawable, because these can happen if icon fails to load too.
